### ISSUE TITLE
Does this block really belong here?

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/Quizzer#10]
https://github.com/geordzNZ/Quizzer/blob/d057e2f7c8d57a45c3b303f4326d6e3f90b8868b/Quizzer/Program.cs#L18-L22
This tries to load your QuizList on every start of your program, regardless of needed or not.

I would only load the file if it is really needed.
Also the condition "if (File.Exists(QUIZ_LIST_FILENAME))" should be part of the "ReadFromQuizFile" function:
This way the user can call it without having to think about if the file is present and the function returns an empty list in this case.

**Comment by geordzNZ** [comment]
Ok I see the point of getting the quiz file at a later stage, ie when the user wants to play or edit a quiz. it's not needed if they open then close it again.
I'd initially put it there to stop the player going too far into the the Quizzer section and also it seemed important to have it there from start up to allow the rest of the functionality. 
But I see also that doesnt really happen now anyways as the 'no quiz check doenst happen until the Quizzer chooses to play a quiz. so that can be reworked.

**Comment by geordzNZ** [comment]
I'd left the File.Exists check out of the function, to the function wouldnt run at all if there was no file to get. Thought that was the way to go, but will move it

**Comment by geordzNZ** [comment]
I've been able to implement that changes to move the get Quiz into the EditorMode file.

**Comment by geordzNZ** [comment]
But when I go to add ReadFromQuzFile() into the top of QuizzerGameMode(), ... I get a bit stuck ... (or maybe I'm just not seeing it) 
At this stage it seems better to me, to check if the file exists and do nothing ... not return an empty file at this point, because if there are no quizzes then the Quizzer cant do anything, so why does it need an empty list.
(I know I can then test the list and if empty return the 'no quiz prompt' but this seems extra)

**Comment by incredibleLeitman** [comment]
You can of course also create a function that lets you check if the file even exists if you think this is more straight forward:D 👍 

But my way of thinking was that having no file at all an having an empty file would result in the same output and can be handled together

**Comment by geordzNZ** [comment]
I'm OK with it as I have it now, which is as you suggested. so I'll close this off now...
